ui/apps/ui/src/app/app-routing.module.ts
ui/apps/ui/src/app/app.module.ts
ui/apps/ui/src/app/layouts/grid-right.component.ts
ui/apps/ui/src/app/layouts/grid.component.ts
ui/apps/ui/src/app/layouts/grid.config.ts
ui/apps/ui/src/app/layouts/layouts.module.ts
ui/apps/ui/src/app/layouts/main-header.component.ts
ui/apps/ui/src/app/pages/dashboard-page/dashboard-page.component.ts

Quick rebuild, not functional and not finished, just to divide the work, further details to be discussed on Call.

feat: Quick rebuild, sketch for further development

---

.github/workflows/add-pr-instance-comment.yaml

chore: add pr instance url comment

---

backend/Dockerfile
ui/apps/ui/src/app/components/widgets/eosc-community/eosc-envri.component.ts
ui/apps/ui/src/app/components/widgets/eosc-community/eosc-escape.component.ts
ui/apps/ui/src/app/components/widgets/eosc-community/eosc-life.component.ts
ui/apps/ui/src/app/components/widgets/eosc-community/eosc-panosc.component.ts
ui/apps/ui/src/app/components/widgets/eosc-community/eosc-sshoc.component.ts
ui/apps/ui/src/app/components/widgets/social-media.component.ts

Removal of not specified options, final version.

Social media Widget #83

---

ui/apps/ui/src/app/components/widgets/videos.component.ts
ui/apps/ui/src/app/widgets/videos/videos-widget.types.ts
ui/apps/ui/src/index.html

- Youtube api call to get last 10 videos added,
- MIssing API _Key ,tbd by email
- Potential move of this call to backend, but first data test and styling on front side, then maybe moved to service (refa phase)

feat: video youtube widget #84

---

ui/apps/ui/src/app/app.module.ts
ui/apps/ui/src/app/components/widgets/upcoming-events.component.ts
ui/apps/ui/src/app/widgets/upcoming-events/upcoming-events-widget.service.ts
ui/apps/ui/src/app/widgets/upcoming-events/upcoming-events-widget.types.ts
ui/apps/ui/src/app/widgets/videos/videos-widget.service.ts
ui/apps/ui/src/environments/environment.common.ts

- preparation for backend integration
- cors error fix by calling through backend and delivering results by proxy
- upcoming events rebuilt for new external api call

feat: upcoming events preparation for be code integration #55

---

ui/apps/ui/src/app/app.module.ts
ui/apps/ui/src/app/components/widgets/upcoming-events.component.ts
ui/apps/ui/src/app/widgets/upcoming-events/upcoming-events-widget.service.ts
ui/apps/ui/src/app/widgets/upcoming-events/upcoming-events-widget.types.ts
ui/apps/ui/src/types/filt.d.ts

- mocked data for navigation 
- navigation added
- missing default data when no upcoming events 
- placeholder for interested and going numbers (to be stored somewhere on our side)-BE/DB

feat: upcoming events mock with navigation #55

---

ui/apps/ui/src/app/app.module.ts
ui/apps/ui/src/app/components/widgets/videos.component.ts

- video navigation added
- connected to video youtube api

feat: video navigation #84

---

backend/Pipfile
backend/Pipfile.lock
backend/app/config.py
backend/app/routes/web/recommendations.py
backend/app/services/web/external_recommendations_service.py
backend/app/services/web/stories_service.py
ui/apps/ui/src/app/components/recommendations-widget/adapter/adapter.ts
ui/apps/ui/src/app/components/recommendations-widget/layouts/navbar/navbar.component.spec.ts
ui/apps/ui/src/app/components/recommendations-widget/layouts/navbar/navbar.component.ts
ui/apps/ui/src/app/components/recommendations-widget/layouts/navbar/navbar.module.ts
ui/apps/ui/src/app/components/recommendations-widget/recommendation.component.ts
ui/apps/ui/src/app/components/recommendations-widget/recommendations-widget.component.ts
ui/apps/ui/src/app/components/recommendations-widget/recommendations-widget.module.ts
ui/apps/ui/src/app/components/recommendations-widget/recommendations.service.ts
ui/apps/ui/src/app/components/recommendations-widget/types.ts
ui/apps/ui/src/app/components/recommendations-widget/utils.ts
ui/apps/ui/src/styles.scss

- Add a top bar into recommendation widgets to change recommendations types
- Extend recommendations types (the same as in Search Service & in the same order)
- Add all recommendations types tab
- Add the possibility to suit the best user recommendations in case of external recommendations failure

feat: add recommndations widget

---

backend/.env.template
backend/app/config.py
backend/app/routes/web/__init__.py
backend/app/routes/web/events.py
backend/app/routes/web/videos.py
docker-compose.yml
ui/apps/ui/src/app/app.module.ts
ui/apps/ui/src/app/components/widgets/upcoming-events.component.ts
ui/apps/ui/src/app/components/widgets/videos.component.ts
ui/apps/ui/src/app/widgets/upcoming-events/upcoming-events-widget.service.ts
ui/apps/ui/src/app/widgets/upcoming-events/upcoming-events-widget.types.ts
ui/apps/ui/src/app/widgets/videos/videos-widget.service.ts
ui/apps/ui/src/app/widgets/videos/videos-widget.types.ts
ui/apps/ui/src/environments/environment.common.ts

- backend for events
- backend for videos
- -7 and +7 months for events , as we dont have empty case,
-10 last videos taken from youtube
- calls goes FE-> BE -> APIs

feat: backend for events #55 and videos #84

---

ui/apps/ui/src/app/components/recommendations-widget/adapter/adapter.ts
ui/apps/ui/src/app/components/recommendations-widget/layouts/tags/tags.component.ts
ui/apps/ui/src/app/components/recommendations-widget/recommendation.component.ts
ui/apps/ui/src/app/components/recommendations-widget/recommendations-widget.component.ts
ui/apps/ui/src/app/components/recommendations-widget/types.ts

- lang tag moved to lower section
- access tags moved to upper section
- upper section with customizable classes and icons

fix: tags new design rearrange #67

---

ui/apps/ui/src/app/components/widgets/upcoming-events.component.ts
ui/apps/ui/src/app/components/widgets/user-profile.component.ts

-hidden buttons
https://github.com/cyfronet-fid/eosc-user-dashboard/issues/128

fix: buttons removed according to #128 issue

---

ui/apps/ui/src/app/components/widgets/eosc-numbers.component.ts
ui/apps/ui/src/app/components/widgets/news.component.ts
ui/apps/ui/src/app/pages/dashboard-page/dashboard-page.component.ts
ui/apps/ui/src/styles.scss

130 style imporovement

---

ui/apps/ui/src/app/components/widgets/eosc-community/eosc-envri.component.ts
ui/apps/ui/src/app/components/widgets/eosc-community/eosc-escape.component.ts
ui/apps/ui/src/app/components/widgets/eosc-community/eosc-life.component.ts
ui/apps/ui/src/app/components/widgets/eosc-community/eosc-panosc.component.ts
ui/apps/ui/src/app/components/widgets/eosc-community/eosc-sshoc.component.ts
ui/apps/ui/src/app/pages/landing-page/landing-page.component.ts
ui/apps/ui/src/styles.scss

mods according to #131

---

ui/Pipfile
ui/apps/ui/src/app/components/widgets/eosc-community/eosc-escape.component.ts
ui/apps/ui/src/app/components/widgets/eosc-community/eosc-life.component.ts
ui/apps/ui/src/app/components/widgets/eosc-community/eosc-panosc.component.ts
ui/apps/ui/src/app/components/widgets/eosc-community/eosc-sshoc.component.ts
ui/apps/ui/src/app/components/widgets/user-profile.component.ts
ui/apps/ui/src/app/pages/dashboard-page/dashboard-page.component.ts
ui/apps/ui/src/app/pages/landing-page/landing-page.component.ts

- fixes for merge issues lint and formattign errors

chore: merge ui commits fixing some lint issues

---

ui/apps/ui/src/app/components/recommendations-widget/layouts/description/description.component.ts
ui/apps/ui/src/app/components/recommendations-widget/layouts/description/description.module.ts

- description sanitization added

feat: sanitize description html #125

---

backend/app/config.py
backend/app/models/api/user_data.py
backend/app/routes/api/user_data.py
ui/apps/ui/src/app/app-routing.module.ts
ui/apps/ui/src/app/app.module.ts
ui/apps/ui/src/app/auth/is-anonymous-user.guard.service.ts
ui/apps/ui/src/app/auth/is-logged-in-user.guard.service.ts
ui/apps/ui/src/app/components/recommendations-widget/recommendation.component.ts
ui/apps/ui/src/app/components/recommendations-widget/recommendations-widget.component.ts
ui/apps/ui/src/app/components/recommendations-widget/recommendations.service.ts
ui/apps/ui/src/app/components/widgets/impact.component.ts
ui/apps/ui/src/app/components/widgets/project.component.ts
ui/apps/ui/src/app/components/widgets/user-profile.component.ts
ui/apps/ui/src/app/pages/dashboard-page/dashboard-favs.component.ts
ui/apps/ui/src/app/pages/dashboard-page/dashboard-favs.module.ts
ui/apps/ui/src/app/pages/dashboard-page/dashboard-page.component.ts
ui/apps/ui/src/app/pages/dashboard-page/dashboard-page.module.ts
ui/apps/ui/src/app/pages/dashboard-page/dashboard-results.component.ts
ui/apps/ui/src/app/pages/dashboard-page/dashboard-results.module.ts
ui/apps/ui/src/app/pages/dashboard-page/dashboard-routing-favs.module.ts
ui/apps/ui/src/app/pages/dashboard-page/dashboard-routing-results.module.ts
ui/apps/ui/src/environments/environment.common.ts
ui/package-lock.json
ui/package.json

feat: backend for fav with postgresql

---

backend/app/services/web/external_recommendations_service.py

[#146] Unify candidates in recommendations request

---

ui/apps/ui/src/app/components/eosc-header/eosc-header.component.ts
ui/apps/ui/src/app/components/recommendations-widget/adapter/adapter.ts
ui/apps/ui/src/app/components/widgets/eosc-numbers.component.ts
ui/apps/ui/src/app/components/widgets/project.component.ts
ui/apps/ui/src/app/components/widgets/user-profile.component.ts
ui/apps/ui/src/app/pages/landing-page/landing-page.component.ts
ui/apps/ui/src/app/pages/privacy-policy/privacy-policy.component.html
ui/apps/ui/src/environments/environment.common.ts
ui/apps/ui/src/environments/environment.prod.ts
ui/apps/ui/src/environments/environment.ts

https://github.com/cyfronet-fid/eosc-user-dashboard/issues/141

Beta UserDashboard

---

ui/apps/ui/src/app/components/recommendations-widget/recommendation.component.ts
ui/apps/ui/src/environments/environment.prod.ts
ui/apps/ui/src/environments/environment.ts

https://github.com/cyfronet-fid/eosc-user-dashboard/issues/153

Fix for dislike enable/disable

---

README.md
backend/app/config.py
backend/app/routes/web/__init__.py
backend/app/routes/web/configuration.py
backend/app/schemas/web/configuration_response.py
ui/apps/ui/src/app/app.module.ts
ui/apps/ui/src/app/app.providers.ts
ui/apps/ui/src/app/components/main-header/main-header.component.ts
ui/apps/ui/src/app/services/config.service.spec.ts
ui/apps/ui/src/app/services/config.service.ts
ui/apps/ui/src/index.html

Set env variables:
```
EOSC_COMMONS_ENV=beta
```

feat: add configurable eosc commons

---

LICENSE

docs: add gpl license
